# This rule is not used by the project taco-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to tacoorder.taco-order.example.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: taco-operator
    app.kubernetes.io/managed-by: kustomize
  name: tacoorder-viewer-role
rules:
- apiGroups:
  - tacoorder.taco-order.example.com
  resources:
  - tacoorders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tacoorder.taco-order.example.com
  resources:
  - tacoorders/status
  verbs:
  - get
